language: ruby
rvm:
- 2.2.5
addons:
  firefox: "46.0"
script:
- bundle exec rake db:test:prepare
- bundle exec rspec
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
