source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'

gem 'pg'
gem 'puma', '~> 3.0'
gem 'jbuilder', '~> 2.5'
gem 'bcrypt', '~> 3.1.7'

gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'nokogiri'
gem 'validates_email_format_of'
gem 'recaptcha', require: 'recaptcha/rails'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'rspec-rails'
  gem 'rails-controller-testing'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'poltergeist'
  gem 'selenium-webdriver', '~> 2.53.0'
  gem 'faker'
end

group :development do
  gem 'web-console'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
